ansible_become_pass: ENC[AES256_GCM,data:GG9G/OM+vt2FylXxXhWn1w==,iv:GND908iPpcaapr2+8ZOVhl+M64884BKMTAam52ZC44A=,tag:0q/EqEUG/lNAmRe06ypEFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age130y7tlj47a6r0p5rlzq62whvga5ucaxeyuzy2e2vflgfxugkvs3sv6d0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRFc4VzBpTEVFNSs4V05M
            QURKbUJBb3VVTGd3ZlUvbDUxa25Nd1o3dnpnCldMdHY2bENsK0RwN01wd0YrNlZM
            TnFiUU5yY2V1a1ZwRmNTSmh6ZS8yS1UKLS0tIFlpUUEvZW8reXlNSTNWYW42S2Nz
            bDhJWS8rbzQ2NEtDMHBYcmJBam55NFUKiX2pZTKirMVS2QvmhJDaVJGsjonwy0SE
            OqjI7aCx6/cxII7DV1F2M4x7tCFGYUiAq8BAJFn0Md0eGMYzUoH4Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-21T03:40:45Z"
    mac: ENC[AES256_GCM,data:lNIemVz8NHSnwNJkgBfTeLY4rv2jB1DuARmhznW8BHj1+emiOdFHmOksYOxxlKYKgUkD7UQSX3oujYAymhNS7/EjGxNDuAqrv8H5bbHClSsm1GCQe37UNovhddK92H/uhgPHsF3TDNovSis8Mvz+vyNHtDHWR/5FcsFdaqEkN/Q=,iv:hNPUzyTM2MjLG1m2b16sLEaUtZiY9UDELyty7/AOFiY=,tag:HEvGY5g1bFGhmQ8O7unwzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
