apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:DYf2Gc3dRfpvXITZ94DtbBlSyXoTWEnb9mj0oFfHtRQUjBEDivEY3g==,iv:eGVaChcI6itZWdVmZZN6mVtQAzwtZtyrwQgcb2k2KMU=,tag:qAFmntPQVcY8yL8y6O5F/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age130y7tlj47a6r0p5rlzq62whvga5ucaxeyuzy2e2vflgfxugkvs3sv6d0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV0NsMHVuVDBuMWx5YktC
            Z0lkd25FcDJ5NEMwSWJ3TSt4RXJicmFmMnlnCjh2STJaZ0VFUTdlL3NjOFZ6QUp1
            WnE0aFFLUmwyU2U0ZFVGN3pmVSsrcjgKLS0tIENSYVhwaVp6bThoOG5OK0creFB3
            YVp6VDlvT1hjT3prb2hsSit6azc0ekkKgQxepBmQ99o+p05kI9La4IwEibGLsd10
            9sv+B5sWThzsb2JebFjs9awDhHmTYOHeky2Z5cfbohs6UsKtVRUeLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T09:41:35Z"
    mac: ENC[AES256_GCM,data:jaVHCLgHtxL5boq3srMmja8JmisOvk8PEel4iV/fAsDFQT5yoCw9XQTaw/LO1eyXPFWllctUbRNg8CJchXgYcAz4IHxLqIRR8aQBIi2ceRBcAasJi3auU2MTo0g/Vk0f6wRyfLOYaSq4mrj/ae1rlJ3KV/MKf8Zm9rUfL+rW5Ck=,iv:EvLVzEwM9K6W5u9odqT3a7to/GCxk4OBZGxSMQ1BiM0=,tag:LsZRquNPIInDcao9mXYTqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
