apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:wX95WpVA5sBNeaE+z8AkvPoRkg9jw24wCOhXYvw77e/tOawdLCemedesVtMfP60PVBoGdnVIJdGSoRJl,iv:OZS81JdLhC2P7y/R9BxK2oWF9AvhEJrCT0TfbRnxwhY=,tag:iLHF8YCiX7bTXxrpO1Sftg==,type:str]
    username: ENC[AES256_GCM,data:Brms9JE=,iv:kUDBXeoKlOEV4W1oj0zBXRQtyQ/5lMJsfFnL11jwwUA=,tag:EkTyHaZXNoU5J5vjhz4/9g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age130y7tlj47a6r0p5rlzq62whvga5ucaxeyuzy2e2vflgfxugkvs3sv6d0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWEh3YnFjV3BJeWxwSHh3
            NlZscGdUUWdvS3Q3R1c5ZGlhYk1kRUc2MmhRCjNPR3FnZmFjZkV1c0NrQ2lGajBV
            VWFUL1ZFbThmbGllRUVVVk1jVXpST1EKLS0tIG5NU3ZDRlVvSE1KMjRCTTZpVnZN
            QjVXVHc0ODZOQ1lHaFBGVnFkQlFlaXcKZJjHhtpsGEYNBhZflJ4eopHsOxAx5R/y
            GMp/cu6vzuvijltaaG884sPTzA+sgCv2DR6OR3CamBL3/lW/Sr/vtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T11:32:12Z"
    mac: ENC[AES256_GCM,data:lbvXLzXUG+paXPGXfAscI3KvjipvCnPDN41f08v7SUYgfWiGP6pAjtm3MNCqZ3M6SwRBXCLeWxRAGz08fLO9tkQFVKzYE+NLZivuHcedV7N7Co8djIDAet2NKQMGKWx9cEj8gQtVbrdht6xgbEKlT/+u72sdJgdsPSZwYGwMcUQ=,iv:WqajVnJoUKhtmZkO4FzuPMwydR8jtCCEgFi81IaKG2E=,tag:na7fjfgIXique9u+0qnM4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
