apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:2OfgXKIWvFA8Ha7wY1VyUtO2ogriKP/UYv/CZjyXIHHdHlC6Iuo39NJMQs3AyPIozycU3ZKQt1Gm9WIp,iv:aniPWN2tmFS+MHIOyqZdsqTAkWzY87QltlaxR1oNTDg=,tag:QpGzXmg21apfL9aFskqk9A==,type:str]
    username: ENC[AES256_GCM,data:b/5apos=,iv:in7XSDW67qrdKN968gw8L7BjAnbHInchqm84/NCEILs=,tag:eTDSybzTxKL+h6V9jevo0A==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age130y7tlj47a6r0p5rlzq62whvga5ucaxeyuzy2e2vflgfxugkvs3sv6d0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMEQ0TGpLT0NSWjlyclEw
            Y3lCWEp3bkxCYW93SldhdUVYbjdETzgrK3lBCmpXUkJrRFlnTnExSnVaOU1DQ0F5
            MVYya3ArUmlKeXdUVE1PRklzWjlYYVEKLS0tIHBOZ1pONHVOZTBCdVo3ck5SK1dR
            VkJ6eitZRTdldlgzMFIxSUJwajhMZDQKtpZqjnondH/8WPHXEIH7sh9sl/tJaxaf
            oQhGEPhddfFRPHJNvOEbmFmHB8mZ3yVrGcjc3jmDqysvLXuKvMqFxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T12:09:08Z"
    mac: ENC[AES256_GCM,data:ZorVAhvv8ec8hrDcXeXWz/oO0hpiIX/Z85u3E3DHcOiB6eHNatOW5AOMedEx6GrhDiMID9dIpvsouLo1So1EGgx8nRlq4RjdDpwoIuY5htx2NJ/i31v3DRcRcbhEs5qPHv/qsmgFbZFBtt4zl0hCwTdcWyfd/Oz7fHH4APNcW3s=,iv:ZI0hP6W/EXVJBUctJ5EV7P0G3jw11OAxnyR7jb5uOD0=,tag:5IihleXj2sOcA3+RM1Nldg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
