apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:A99VkIjJ0bfgjTDhrlMFAXt3UQ==,iv:OR0Jg22TiqJOQGWfroyXNhrHA9bxYW5qeghDR/DPkdY=,tag:lRLCIAW+4kvdY/PeRJcKsQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vvkWm+fi9Bt/y4z1IdkeO0UcAH82rVjLSOeH8kNCyCBE+laq,iv:Al3LJwGeDAjxk/lHANNtoPkhVpDHf1j3cFQJYU8+OnU=,tag:uHlAAfEhvsWOuW6MYVeDkw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:U0YZpZDb7Iy1RDlwSH+xl8A=,iv:jCQ+F+dbjc8RvFg6SPkyUkJC2G1+aCApo8P2SGOtcnc=,tag:g6EIpRDQ+cuBO4afN9jPJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age130y7tlj47a6r0p5rlzq62whvga5ucaxeyuzy2e2vflgfxugkvs3sv6d0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cTJma1FJREhyYnpURUM5
            eERZUmJuOEJkQVVFMXEyU2JKb2hESVVuOFJVCkJOWjNlSFBtNjNwYWZ5SGVkWFVX
            cmRuUFlUWnZzNzc4cVozNUxKV3Y4bU0KLS0tIDh5aThSdG1QWDNGajRuZTAwZ3lF
            c2k2OEx1bS9TVmx3R2hpWVM0cHhwV0UKMRt65pVSwEYKnQPz/bFgRP92+8PqIED6
            MKXW7BQtpCKtRsyes1o25LMpcOOBsOMjXdru6Yd5i7mUgS7OGHwhdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T11:31:42Z"
    mac: ENC[AES256_GCM,data:C7YcUr2iXp8pc4MlNdYxUgTatt8zOYrX/VY7g0BpIGmRzYP03ojHBrMaH3lDDo8f9OZ/ZL3nRoLgFHjxPiZYQT+3o5kZ9oBn/DxpZE2GXXWTdZpDTGnO3ZAzEm2DTyJyMxw0RdyYc6iN4pbgdd2vhZJzkLQs7jafT0OcYaXSl+0=,iv:9TIozh/xF6KWxNhHDROwL79q9cJ1yT4gn5s99JQ9kkU=,tag:kdkV7QZYzht0pXMnJrEnBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
