apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:trGobOhxmnT5hENFMsdCQ3EgBg==,iv:k8+0szksmgKSrCnz6TEpVhwakQSuFGC7n5XnkmrAwp8=,tag:I0r1sUO0eLRJjE2C9GQrJQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6SmevGDRPXVbNottRuhYfOB/KeXIBNLbyPrD4VF5t0iKNtVI,iv:T6dXG+PilErkxwAOFc2rChwErS/kLEhlT65ApxZ4jpk=,tag:zZbRSneJuBhXQK1QfNs48Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:JBNb9Re/8g/AP1f4pFEW5+E=,iv:w78wq+dUoGA6BQLLaWwSbX/ibxKuImwtNwCr18FdwGI=,tag:8M+ZNs0rOQhRNlM/y40ejQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age130y7tlj47a6r0p5rlzq62whvga5ucaxeyuzy2e2vflgfxugkvs3sv6d0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL2hJOHVtK0ZnMVI4VWk2
            VTlKS3B1YXdEUGZNSVF6dkEwNklad2FrV3hZCk5kKy9NL00zK1BZeWV1YlF2U1dX
            SzV4b3YvVjZ4NEhzdzNBTWEwc2g2enMKLS0tIGl0Z1lvTC9wSXRZOUNZYVJtVGlS
            dy9jRXJXamR0Ui8yeFdKVlNPclNJZjQKlrsoFV+/4267dr5E507MbVI0wZIcm8Zr
            M/I5K0dLbl36M9hlvDWNAzCJry0dEN9wRii1PSQ3aKGd0njCgTkrkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-21T03:42:18Z"
    mac: ENC[AES256_GCM,data:9Cu8ckq4PVhUEribComEGSArPem7XePkKlmge2IaGgV4ZvAjRYomrrGp9n91RfB2cxYeP5MNRGwAcqKVctcpQdeIh1EkNLRpxjsT/lSMvKR4B+BKBnQeFPTIDVtAsjOTMzQ/W/h+rxYsV1FfV9Qw1gQgBJZPsXQubtEo4j2O4YY=,iv:9agfo8zAbSGvuJA1LlHnudoOk2vH/UwhdsubjxPyzsE=,tag:TbhwV/sT4d+yEyvpwEgCWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
