apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:6WMntkxG0ej1wkbT9CVPXAREJrXcwu3gVFCY69YoqthYNsq3,iv:4EIdFXupRDivSv5iTO5fJbyZL+8nZ3qWfRtQuHHdbaQ=,tag:Mfxfz2Hh+W1x1JP98mG0jg==,type:str]
    credentials.json: ENC[AES256_GCM,data:yqWf52x4vj8Av99eIU9mNkRV9mKA5fEghj8urob7AaiqzBmNXJ6gipx/uwQ63ArIzkjq1A2BkbPzDgbYbX21sb+TxPPu07jYlShI/oSe3Jn64JCSiXNx2bgCjbeIqS42z4vmaVxvlpC3hz+y/ETGyCyVuVGOHXgBLZk9aFymaDoYfAw4tIZKjn+nNR4jGBDdg2KszVgPJ/vJij8gh3T7T+Si+HDcQTVvME0DsPFdQw==,iv:ApgDSvPcETCr4bLNV4Wv9qVc3OatJwO1TMOkLFGCw6o=,tag:PzBEFfNRXX5+FPj4nYO52g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age130y7tlj47a6r0p5rlzq62whvga5ucaxeyuzy2e2vflgfxugkvs3sv6d0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y29BekZDU1pqNGVTQ2pS
            Uitpdm5nY1pSQW5rNGFVbWFyN0FrMnF2eXhNCit5QmpxeEtIUEdBVVZRVnRKS3p0
            dmVGVzZIZ3lZQzIxWjY4ZGlMTXhzSU0KLS0tIHovbTEvcjM2WTM3VG1VS2ZRZnpR
            NlJVUitRa29xU0RKRmNOSHpzRHlSMk0KjyuS37FyZY1ArTRHCzzbcj3mafHakYqA
            e1/6rBWH7UT6Fnm7UaeYLtNR/Egc/9KuZG7Vbrj9h51teK2M7/EvqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T11:31:40Z"
    mac: ENC[AES256_GCM,data:fRAts0cRmRXTYAEhd2wBg56v4AIShnHP/0EsP5//OeyNgfgLtSumhVus6bgFgvMQiv3lDQX3EY+zSoThZKr5zQJOGTM9jERjBwMT3X9cyF9RadV9PMTRHy0eBLMLHSkeYKmVMvFp8glNVQpXoqVyTBgRfArITqFDPpUofBgH+tA=,iv:O5goHrwYI8WC/T26GYQRUUN3hgfTgH0PcTxwx0rI8A4=,tag:zJopJDgSO0ZVG3fIaynP+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
