apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:TaAftElaTLAVyGaUQXlSboip9AtfLesEpDQytmneohHwp6Ya,iv:BQoEYYMwlwpIqy0tdrH7yShtz3aQ793rdMm3kmN2Th8=,tag:t9F+8JtLrLJR2ATxS+sh4A==,type:str]
    credentials.json: ENC[AES256_GCM,data:CO2Jnq2tytlcyiq+Ekg3dip1qB35qus2lh4pqpSXPnURSHfloBmvaA1rIbTFHynkuwQnRAwV9W3mOUsFNVPCF3wnBFfpw43S9hXERLPBsOUmcEg27eDNJmk2us5Gq5bDXwLJ5lv2Al7GBZdKLufykuQYCkSQuYSiUNg+OYb+lfM3hHuEKaQZfmIw88Wq6PyRYu1Qf+ZGlJuPHsIovbovDmBEabM3U3en1s3ZhjbF8A==,iv:qpTKFuJ1x2LWqPcdNEaiEc/uUCGvFtaae53kVfchPbA=,tag:T9h+gnnUr53SUZ5kIjY2sA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age130y7tlj47a6r0p5rlzq62whvga5ucaxeyuzy2e2vflgfxugkvs3sv6d0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NStYdm5NUi9DeS9wcTF0
            UnA5R2huRjhyUEwvMnFyTk9tYUZNKyttV2hNCkhsUWVLMTBndVFIek9GalBTckw2
            ZncwcWNoSExWMHlzN2tTdWlvQzBiaXMKLS0tIEF2V0dId3AzTFJEeHEyWUFiRGVI
            NktaOHY0L3QyZzcwd3NreTNOQjVVV2MKk3Uo1GqjOOnJSqxGCCU3no0TqcI0PCId
            6pm9HTM8ddqr3L2qW7QLkIIlhcSMABKOj3boMVMownw8nejDbBZDSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T09:41:36Z"
    mac: ENC[AES256_GCM,data:BcLGiwD7QAJbm0r465qJAWKGUrISpieSQdiYbd4OpbjD3FPYZQXYrgQnHsMoTs8pXS2ZKQHPOyFsFMy2o6/hRxXenQLDtXT0G8grBGeKBNVnhaW+z70yCmFNOjASMAOk0txjyDVtD8/qCHAL3imQoOfXpsOWi+dTKNTdg7aXgeg=,iv:Nxc87Al4Nyr4ih1IvRKCHjEa5C7mImMZ6tYwTSdHIaI=,tag:lYP4SS5EGyjHPvWOZQplGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
